<a href="https://colab.research.google.com/github/felipe-cp/DSA-Python/blob/master/Intro_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Esses exemplos sofreram algumas alterações no TensorFlow 2.0, por isso estamos usando o TF 1.x como um comportamento no TF 2.0
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [ ]:
tf.__version__

'2.2.0'

In [ ]:
# Criar um tensor
# Esse tensor é adicionado como um nó ao grafo
hello = tf.constant('Hello, TensorFlow!!')

In [ ]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [ ]:
# Inicia a sessão TensorFlow
sess = tf.Session()

In [ ]:
print(sess)

In [ ]:
print(sess.run(hello))

b'Hello, TensorFlow!!'


In [ ]:
const_a = tf.constant(5)
const_b = tf.constant(9)

In [ ]:
print(const_a)

Tensor("Const_1:0", shape=(), dtype=int32)


In [ ]:
total = const_a + const_b

In [ ]:
print(total)

Tensor("add:0", shape=(), dtype=int32)


In [ ]:
with tf.Session() as sess:
  print('\nA soma do node1 com o node2 é: %f' % sess.run(total))


A soma do node1 com o node2 é: 14.000000


In [ ]:
# Tudo isso pode ser resumido da seguinte forma: 
node1 = tf.constant(20, dtype=tf.int32)
node2 = tf.constant(30, dtype=tf.int32)
node3 = tf.add(node1, node2)

# Criar a sessão TF
sess = tf.Session()

# Executa o grafo
print("\nA soma do node1 com o node2 é:", sess.run(node3))

# Fecha a sessão
sess.close()


A soma do node1 com o node2 é: 50


In [ ]:
# Tensores randômicos
rand_a = tf.random_normal([3], 2.0)
rand_b = tf.random_uniform([3], 1.0, 4.0)
print(rand_a)
print(rand_b)

Tensor("random_normal:0", shape=(3,), dtype=float32)
Tensor("random_uniform:0", shape=(3,), dtype=float32)


In [ ]:
# Subtração
diff = tf.subtract(rand_a, rand_b)
with tf.Session() as sess:
	print('\nTensor rand_a: ', sess.run(rand_a))
	print('\nTensor rand_b: ', sess.run(rand_b))
	print('\nSubtração entre os dois tensores é: ', sess.run(diff))


Tensor rand_a:  [1.751864  3.1307645 2.3862913]

Tensor rand_b:  [3.0687227 1.284469  1.912657 ]

Subtração entre os dois tensores é:  [-1.9518921 -0.4499687  0.7236186]


In [ ]:
# Divisão
node1 = tf.constant(21, dtype=tf.int32)
node2 = tf.constant(7, dtype=tf.int32)
div = tf.div(node1, node2)
# Sessão TF
with tf.Session() as sess:
	print('\nDivisão entre os 2 tensores é: ', sess.run(div))

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.

Divisão entre os 2 tensores é:  3


In [ ]:
# Multiplicação de tensores
# Criando os tensores 
tensor_a = tf.constant([[4., 2.]])
tensor_b = tf.constant([[3.], [7.]])
print(tensor_a)
print(tensor_b)

Tensor("Const_7:0", shape=(1, 2), dtype=float32)
Tensor("Const_8:0", shape=(2, 1), dtype=float32)


In [ ]:
# tf.multiply(X, Y) executa multiplicação element-wise (multiplicação de matrizes)
prod = tf.multiply(tensor_a, tensor_b)

# Executa a sessão
with tf.Session() as sess:
	print('\ntensor_a: \n', sess.run(tensor_a))
	print('\ntensor_b: \n', sess.run(tensor_b))
	print('\nProduto Element-wise entre os tensores: \n', sess.run(prod))


tensor_a: 
 [[4. 2.]]

tensor_b: 
 [[3.]
 [7.]]

Produto Element-wise entre os tensores: 
 [[12.  6.]
 [28. 14.]]


In [ ]:
# Outro exemplo de multiplicação de matrizes
mat_a = tf.constant([[2, 3], [9, 2], [4, 5]])
mat_b = tf.constant([[6, 4, 5], [3, 7, 2]])
print(mat_a)
print(mat_b)

Tensor("Const_9:0", shape=(3, 2), dtype=int32)
Tensor("Const_10:0", shape=(2, 3), dtype=int32)


In [ ]:
# tf.matmul(X, Y) executa multiplicação entre matrizes 
mat_prod = tf.matmul(mat_a, mat_b)
# Executa a sessão
with tf.Session() as sess:
	print('\nTensor mat_a: \n', sess.run(mat_a))
	print('\nTensor mat_b: \n', sess.run(mat_b))
	print('\nProduto Element-wise entre os Tensores (Matrizes): \n', sess.run(mat_prod))


Tensor mat_a: 
 [[2 3]
 [9 2]
 [4 5]]

Tensor mat_b: 
 [[6 4 5]
 [3 7 2]]

Produto Element-wise entre os Tensores (Matrizes): 
 [[21 29 16]
 [60 50 49]
 [39 51 30]]


In [ ]:
# Tensores com variáveis 
# Criando o tensor com zeros
node = tf.Variable(tf.zeros([2, 2]))

# Executando o grafo computacional
with tf.Session() as sess: 
	# Inicializando as variáveis
	sess.run(tf.global_variables_initializer())
	# Avaliando o node
	print("\nTensor original: \n", sess.run(node))
	# Adição element-wise no tensor
	node = node.assign(node + tf.ones([2, 2]))
	# Avaliando o node novamente
	print("\nTensor depois da adição: \n", sess.run(node))


Tensor original: 
 [[0. 0.]
 [0. 0.]]

Tensor depois da adição: 
 [[1. 1.]
 [1. 1.]]


In [ ]:
# Usando Placeholders
# Crinado nodes no grafo computacional
a = tf.placeholder(tf.int32, shape=(3,1))
b = tf.placeholder(tf.int32, shape=(1,3))
c = tf.matmul(a,b)

# Executando o grafo computacional
with tf.Session() as sess:
	print(sess.run(c, feed_dict={a:[[3], [2], [1]], b:[[1,2,3]]})) # feed_dict permite que seja possível alimentar os tensores com qualquer valor

[[3 6 9]
 [2 4 6]
 [1 2 3]]
